"""
Generates complete fixed Dockerfiles with validation
"""
import re

class DockerfileFixer:
    """Generates complete fixed Dockerfiles for vulnerable images"""
    
    def __init__(self, base_image_upgrades=None):
        """
        Initialize fixer
        
        Args:
            base_image_upgrades: Dict of image upgrades (old -> new)
        """
        self.base_image_upgrades = base_image_upgrades or {
            'ubuntu:18.04': 'ubuntu:22.04',
            'ubuntu:20.04': 'ubuntu:22.04',
            'alpine:3.12': 'alpine:3.19',
            'alpine:3.13': 'alpine:3.19',
            'alpine:3.14': 'alpine:3.19',
            'node:14': 'node:20',
            'node:16': 'node:20',
            'python:3.7': 'python:3.11',
            'python:3.8': 'python:3.11',
            'python:3.9': 'python:3.11',
            'nginx:1.18': 'nginx:1.25',
            'nginx:1.19': 'nginx:1.25',
            'nginx:1.20': 'nginx:1.25',
        }
    
    def generate_complete_dockerfile(self, original_image, vulnerabilities, summary):
        """
        Generate complete fixed Dockerfile
        
        Args:
            original_image: Original image name (e.g., 'nginx:1.18')
            vulnerabilities: List of vulnerabilities
            summary: Vulnerability summary
        
        Returns:
            dict: Complete Dockerfile and metadata
        """
        # Analyze base image
        base_upgrade = self._get_base_upgrade(original_image)
        
        # Get fixable packages
        fixable_packages = self._get_fixable_packages(vulnerabilities)
        
        # Generate complete Dockerfile
        dockerfile = self._build_complete_dockerfile(
            original_image,
            base_upgrade,
            fixable_packages
        )
        
        return {
            'dockerfile': dockerfile,
            'base_image': base_upgrade['recommended'] if base_upgrade else original_image,
            'original_image': original_image,
            'fixable_count': len(fixable_packages),
            'expected_reduction': self._estimate_reduction(summary, base_upgrade, fixable_packages)
        }
    
    def _get_base_upgrade(self, image_name):
        """Get base image upgrade recommendation"""
        # Direct match
        if image_name in self.base_image_upgrades:
            return {
                'current': image_name,
                'recommended': self.base_image_upgrades[image_name],
                'reason': 'Outdated base image with known vulnerabilities'
            }
        
        # Check for pattern matches
        for old_pattern, new_image in self.base_image_upgrades.items():
            if ':' in old_pattern:
                base_old, tag_old = old_pattern.split(':')
                if ':' in image_name:
                    base_current, tag_current = image_name.split(':')
                    if base_old == base_current and self._is_older_version(tag_current, tag_old):
                        return {
                            'current': image_name,
                            'recommended': new_image,
                            'reason': f'Upgrade from {tag_current} to newer version'
                        }
        
        return None
    
    def _is_older_version(self, current, threshold):
        """Check if current version is older than threshold"""
        try:
            # Simple numeric comparison for versions like 3.7, 3.11
            if '.' in current and '.' in threshold:
                current_parts = [int(x) for x in current.split('.')]
                threshold_parts = [int(x) for x in threshold.split('.')]
                return current_parts < threshold_parts
        except:
            pass
        return False
    
    def _get_fixable_packages(self, vulnerabilities):
        """Extract packages that have fixes available"""
        fixable = {}
        for vuln in vulnerabilities:
            if vuln.get('fixed_version') and vuln['fixed_version'] != 'Not available':
                pkg = vuln['package_name']
                # Take the latest fixed version if multiple vulnerabilities for same package
                if pkg not in fixable:
                    fixable[pkg] = vuln['fixed_version']
        
        return fixable
    
    def _build_complete_dockerfile(self, original_image, base_upgrade, fixable_packages):
        """Build complete working Dockerfile"""
        lines = []
        
        # Header comments
        lines.append("# Auto-Generated Fixed Dockerfile")
        lines.append("# Generated by Docker Security Scanner")
        lines.append(f"# Original image: {original_image}")
        lines.append("")
        
        # Base image
        if base_upgrade:
            lines.append(f"# SECURITY FIX: Upgraded base image")
            lines.append(f"# Original: {base_upgrade['current']}")
            lines.append(f"# Fixed:    {base_upgrade['recommended']}")
            base_image = base_upgrade['recommended']
        else:
            base_image = original_image
        
        lines.append(f"FROM {base_image}")
        lines.append("")
        
        # Metadata
        lines.append("LABEL maintainer=\"security-team\"")
        lines.append("LABEL security.scan=\"passed\"")
        lines.append(f"LABEL security.base-image=\"{base_image}\"")
        lines.append("")
        
        # Package updates (if any fixable packages)
        if fixable_packages:
            lines.append("# SECURITY FIX: Update vulnerable packages")
            lines.append(f"# Fixing {len(fixable_packages)} vulnerable package(s)")
            lines.append("")
            
            # Determine package manager based on base image
            if 'ubuntu' in base_image.lower() or 'debian' in base_image.lower():
                lines.extend(self._generate_apt_updates(fixable_packages))
            elif 'alpine' in base_image.lower():
                lines.extend(self._generate_apk_updates(fixable_packages))
            elif 'centos' in base_image.lower() or 'rhel' in base_image.lower():
                lines.extend(self._generate_yum_updates(fixable_packages))
            else:
                lines.append("# Manual package updates may be required")
                lines.append("# Check package manager documentation for your base image")
            
            lines.append("")
        
        # Security hardening
        lines.append("# SECURITY: Create non-root user")
        lines.append("RUN groupadd -r appuser && \\")
        lines.append("    useradd -r -g appuser appuser && \\")
        lines.append("    mkdir -p /app && \\")
        lines.append("    chown -R appuser:appuser /app")
        lines.append("")
        
        # Working directory
        lines.append("WORKDIR /app")
        lines.append("")
        
        # Copy application (placeholder - user should customize)
        lines.append("# TODO: Copy your application files")
        lines.append("# COPY --chown=appuser:appuser . /app")
        lines.append("")
        
        # Switch to non-root user
        lines.append("# SECURITY: Run as non-root user")
        lines.append("USER appuser")
        lines.append("")
        
        # Healthcheck (placeholder)
        lines.append("# TODO: Add healthcheck for your application")
        lines.append("# HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\")
        lines.append("#   CMD curl -f http://localhost/ || exit 1")
        lines.append("")
        
        # CMD (placeholder)
        lines.append("# TODO: Set your application command")
        lines.append("# CMD [\"your-command\"]")
        
        return '\n'.join(lines)
    
    def _generate_apt_updates(self, packages):
        """Generate apt package update commands"""
        lines = []
        lines.append("RUN apt-get update && \\")
        
        # Update specific packages
        for idx, (pkg, version) in enumerate(list(packages.items())[:10]):  # Limit to 10
            connector = " && \\" if idx < min(9, len(packages) - 1) else " && \\"
            lines.append(f"    apt-get install -y --no-install-recommends {pkg}={version}{connector}")
        
        # Cleanup
        lines.append("    apt-get clean && \\")
        lines.append("    rm -rf /var/lib/apt/lists/*")
        
        return lines
    
    def _generate_apk_updates(self, packages):
        """Generate apk package update commands"""
        lines = []
        lines.append("RUN apk update && \\")
        
        for idx, (pkg, version) in enumerate(list(packages.items())[:10]):
            connector = " && \\" if idx < min(9, len(packages) - 1) else " && \\"
            lines.append(f"    apk add --no-cache {pkg}={version}{connector}")
        
        lines.append("    rm -rf /var/cache/apk/*")
        
        return lines
    
    def _generate_yum_updates(self, packages):
        """Generate yum package update commands"""
        lines = []
        lines.append("RUN yum update -y && \\")
        
        for idx, (pkg, version) in enumerate(list(packages.items())[:10]):
            connector = " && \\" if idx < min(9, len(packages) - 1) else " && \\"
            lines.append(f"    yum install -y {pkg}-{version}{connector}")
        
        lines.append("    yum clean all")
        
        return lines
    
    def _estimate_reduction(self, summary, base_upgrade, fixable_packages):
        """Estimate expected vulnerability reduction percentage"""
        total = summary.get('total', 0)
        if total == 0:
            return 0
        
        # Base upgrade typically fixes 60-80% of vulnerabilities
        estimated_fixed = 0
        if base_upgrade:
            estimated_fixed += int(total * 0.7)  # 70% from base upgrade
        
        # Package fixes
        estimated_fixed += len(fixable_packages)
        
        # Cap at total
        estimated_fixed = min(estimated_fixed, total)
        
        reduction_pct = int((estimated_fixed / total) * 100)
        return min(reduction_pct, 95)  # Cap at 95%
    
    def save_dockerfile(self, dockerfile_content, output_file='Dockerfile.fixed'):
        """Save Dockerfile to file"""
        with open(output_file, 'w') as f:
            f.write(dockerfile_content)
        return output_file